### ISSUE TITLE
Unable to unserialize unknown type 3

### ISSUE THREAD

**Issue by johnny901114** [kayahr/pherialize#4]
my content is a:2:{s:4:"text";s:392:"阴道炎疾病伴随着许多女性，这个病症为我们女性带来无尽烦恼，大家都知道得了阴道炎，外阴常常会瘙痒，阴道分泌物较多让我们饱受其苦。之前我有咨询过医生，医生建议：预防为主治疗为辅，实际就是告诉我们预防很重要，那预防阴道炎有那先方法呢？在此与大家分享女性阴道炎预防方法";s:3:"img";s:0:"";} I test your project , throw follow exception : 
Exception in thread "main" de.ailis.pherialize.exceptions.UnserializeException: Unable to unserialize unknown type 3
    at de.ailis.pherialize.Unserializer.unserializeObject(Unserializer.java:128)
    at de.ailis.pherialize.Unserializer.unserializeArray(Unserializer.java:263)
    at de.ailis.pherialize.Unserializer.unserializeObject(Unserializer.java:121)
    at de.ailis.pherialize.Pherialize.unserialize(Pherialize.java:128)
    at de.ailis.pherialize.test.Test.main(Test.java:34)

**Comment by killer0217** [comment]
This is the problem of Chinese character in unserialization.
You can find my solution in issue 14.
