### ISSUE TITLE
Unable to unserialize unknown type :

### ISSUE THREAD

**Issue by gmercey** [kayahr/pherialize#5]
Hi,

Here my serialize string. I don't have any problem unserialize it with PHP, but impossible to do it with JAVA :

a:6:{s:5:"width";i:500;s:6:"height";i:368;s:14:"hwstring_small";s:23:"height='94' width='128'";s:4:"file";s:35:"tumblr_inline_mrtxtyrsTn1qz4rgp.jpg";s:5:"sizes";a:2:{s:9:"thumbnail";a:4:{s:4:"file";s:43:"tumblr_inline_mrtxtyrsTn1qz4rgp-150x150.jpg";s:5:"width";i:150;s:6:"height";i:150;s:9:"mime-type";s:10:"image/jpeg";}s:6:"medium";a:4:{s:4:"file";s:43:"tumblr_inline_mrtxtyrsTn1qz4rgp-300x220.jpg";s:5:"width";i:300;s:6:"height";i:220;s:9:"mime-type";s:10:"image/jpeg";}}s:10:"image_meta";a:10:{s:8:"aperture";i:0;s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";i:0;s:9:"copyright";s:104:"TM & © 2013 Twentieth Century Fox Film Corporation.  All Rights Reserved.  Not for sale or duplication.";s:12:"focal_length";i:0;s:3:"iso";i:0;s:13:"shutter_speed";i:0;s:5:"title";s:0:"";}}

Unable to unserialize unknown type :
de.ailis.pherialize.exceptions.UnserializeException: Unable to unserialize unknown type :
    at de.ailis.pherialize.Unserializer.unserializeObject(Unserializer.java:109)
    at de.ailis.pherialize.Unserializer.unserializeArray(Unserializer.java:243)
    at de.ailis.pherialize.Unserializer.unserializeObject(Unserializer.java:102)
    at de.ailis.pherialize.Unserializer.unserializeArray(Unserializer.java:245)
    at de.ailis.pherialize.Unserializer.unserializeObject(Unserializer.java:102)
    at de.ailis.pherialize.Pherialize.unserialize(Pherialize.java:83)

**Comment by 350050183** [comment]
It is because of not support key=>value format.
